
package serviceSoap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://services.mspi.issatso.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param idCmnt
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCommentaire", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.DeleteCommentaire")
    @ResponseWrapper(localName = "deleteCommentaireResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.DeleteCommentaireResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/deleteCommentaireRequest", output = "http://services.mspi.issatso.org/SoapService/deleteCommentaireResponse")
    public void deleteCommentaire(
        @WebParam(name = "idCmnt", targetNamespace = "")
        Integer idCmnt);

    /**
     * 
     * @param idcmnt
     * @return
     *     returns serviceSoap.Commentaire
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOneCommentaire", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.FindOneCommentaire")
    @ResponseWrapper(localName = "findOneCommentaireResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.FindOneCommentaireResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/findOneCommentaireRequest", output = "http://services.mspi.issatso.org/SoapService/findOneCommentaireResponse")
    public Commentaire findOneCommentaire(
        @WebParam(name = "idcmnt", targetNamespace = "")
        Integer idcmnt);

    /**
     * 
     * @param idSmg
     * @return
     *     returns java.util.List<serviceSoap.Commentaire>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommentaireByMessage", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.GetCommentaireByMessage")
    @ResponseWrapper(localName = "getCommentaireByMessageResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.GetCommentaireByMessageResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/getCommentaireByMessageRequest", output = "http://services.mspi.issatso.org/SoapService/getCommentaireByMessageResponse")
    public List<Commentaire> getCommentaireByMessage(
        @WebParam(name = "IdSmg", targetNamespace = "")
        Integer idSmg);

    /**
     * 
     * @param emailAuteur
     * @return
     *     returns java.util.List<serviceSoap.Message>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessagesByAuteur", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.GetMessagesByAuteur")
    @ResponseWrapper(localName = "getMessagesByAuteurResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.GetMessagesByAuteurResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/getMessagesByAuteurRequest", output = "http://services.mspi.issatso.org/SoapService/getMessagesByAuteurResponse")
    public List<Message> getMessagesByAuteur(
        @WebParam(name = "emailAuteur", targetNamespace = "")
        String emailAuteur);

    /**
     * 
     * @param commentaire
     */
    @WebMethod
    @RequestWrapper(localName = "updateCommentaire", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.UpdateCommentaire")
    @ResponseWrapper(localName = "updateCommentaireResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.UpdateCommentaireResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/updateCommentaireRequest", output = "http://services.mspi.issatso.org/SoapService/updateCommentaireResponse")
    public void updateCommentaire(
        @WebParam(name = "commentaire", targetNamespace = "")
        Commentaire commentaire);

    /**
     * 
     * @param auteur
     * @return
     *     returns serviceSoap.Auteur
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAuteur", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.AddAuteur")
    @ResponseWrapper(localName = "addAuteurResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.AddAuteurResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/addAuteurRequest", output = "http://services.mspi.issatso.org/SoapService/addAuteurResponse")
    public Auteur addAuteur(
        @WebParam(name = "auteur", targetNamespace = "")
        Auteur auteur);

    /**
     * 
     * @param commentaire
     */
    @WebMethod
    @RequestWrapper(localName = "addCommentaire", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.AddCommentaire")
    @ResponseWrapper(localName = "addCommentaireResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.AddCommentaireResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/addCommentaireRequest", output = "http://services.mspi.issatso.org/SoapService/addCommentaireResponse")
    public void addCommentaire(
        @WebParam(name = "commentaire", targetNamespace = "")
        Commentaire commentaire);

    /**
     * 
     * @param message
     */
    @WebMethod
    @RequestWrapper(localName = "addMessage", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.AddMessage")
    @ResponseWrapper(localName = "addMessageResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.AddMessageResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/addMessageRequest", output = "http://services.mspi.issatso.org/SoapService/addMessageResponse")
    public void addMessage(
        @WebParam(name = "message", targetNamespace = "")
        Message message);

    /**
     * 
     * @param idAuteur
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAuteur", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.DeleteAuteur")
    @ResponseWrapper(localName = "deleteAuteurResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.DeleteAuteurResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/deleteAuteurRequest", output = "http://services.mspi.issatso.org/SoapService/deleteAuteurResponse")
    public void deleteAuteur(
        @WebParam(name = "idAuteur", targetNamespace = "")
        String idAuteur);

    /**
     * 
     * @param idSmg
     */
    @WebMethod
    @RequestWrapper(localName = "deleteMessage", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.DeleteMessage")
    @ResponseWrapper(localName = "deleteMessageResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.DeleteMessageResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/deleteMessageRequest", output = "http://services.mspi.issatso.org/SoapService/deleteMessageResponse")
    public void deleteMessage(
        @WebParam(name = "idSmg", targetNamespace = "")
        Integer idSmg);

    /**
     * 
     * @param email
     * @return
     *     returns serviceSoap.Auteur
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOneAuteur", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.FindOneAuteur")
    @ResponseWrapper(localName = "findOneAuteurResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.FindOneAuteurResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/findOneAuteurRequest", output = "http://services.mspi.issatso.org/SoapService/findOneAuteurResponse")
    public Auteur findOneAuteur(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param idSmg
     * @return
     *     returns serviceSoap.Message
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOneMessage", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.FindOneMessage")
    @ResponseWrapper(localName = "findOneMessageResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.FindOneMessageResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/findOneMessageRequest", output = "http://services.mspi.issatso.org/SoapService/findOneMessageResponse")
    public Message findOneMessage(
        @WebParam(name = "idSmg", targetNamespace = "")
        Integer idSmg);

    /**
     * 
     * @return
     *     returns java.util.List<serviceSoap.Auteur>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAuteur", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.GetAllAuteur")
    @ResponseWrapper(localName = "getAllAuteurResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.GetAllAuteurResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/getAllAuteurRequest", output = "http://services.mspi.issatso.org/SoapService/getAllAuteurResponse")
    public List<Auteur> getAllAuteur();

    /**
     * 
     * @param auteur
     */
    @WebMethod
    @RequestWrapper(localName = "updateAuteur", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.UpdateAuteur")
    @ResponseWrapper(localName = "updateAuteurResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.UpdateAuteurResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/updateAuteurRequest", output = "http://services.mspi.issatso.org/SoapService/updateAuteurResponse")
    public void updateAuteur(
        @WebParam(name = "auteur", targetNamespace = "")
        Auteur auteur);

    /**
     * 
     * @param message
     */
    @WebMethod
    @RequestWrapper(localName = "updateMessage", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.UpdateMessage")
    @ResponseWrapper(localName = "updateMessageResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.UpdateMessageResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/updateMessageRequest", output = "http://services.mspi.issatso.org/SoapService/updateMessageResponse")
    public void updateMessage(
        @WebParam(name = "message", targetNamespace = "")
        Message message);

    /**
     * 
     * @return
     *     returns java.util.List<serviceSoap.Message>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllMessage", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.FindAllMessage")
    @ResponseWrapper(localName = "findAllMessageResponse", targetNamespace = "http://services.mspi.issatso.org/", className = "serviceSoap.FindAllMessageResponse")
    @Action(input = "http://services.mspi.issatso.org/SoapService/findAllMessageRequest", output = "http://services.mspi.issatso.org/SoapService/findAllMessageResponse")
    public List<Message> findAllMessage();

}
